theme: jekyll-theme-minimal
logo: /assets/img/photo.jpeg
title: Leonardo Mouta
description: I am a 3rd year exchange student at ISAE-SUPAERO (France) currently specializing in autonomous systems. Former student at Brazil's Aeronautics Institute of Technology (ITA). Particularly interested in UAVs of all types. Other interests include Military History, literature and bad jokes.
